spring.application.name=service-traitement

server.port=8091
spring.cloud.version=2023.0.1

eureka.client.use-dns-for-fetching-service-urls=false
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.prefer-ip-address=true

spring.cloud.inetutils.preferred-networks=192.168,10.0
spring.cloud.inetutils.default-hostname=localhost
spring.cloud.inetutils.default-ip-address=127.0.0.1

spring.influx.url=http://localhost:8086
spring.influx.token=7xZH8BLUeNr7j8pHIWkMv38S7PZf0-FqFftZ-lejEPBIgDG-hWPvWJN_UYmAVVI8FH3jECTWhQrRuaxN9-b5jQ==
spring.influx.org=Academie
spring.influx.bucket=TOCKEN

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

logging.level.com.influxdb=DEBUG
