spring.application.name=service-alerte
server.port=8092

# Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.instance.ip-address=127.0.0.1

# InfluxDB
influx.url=http://localhost:8086
influx.token=-paaZ3-GVK72WmIU9KlXzupan3RCSfG4XcAuBbQOKvPHyJboyLPsg4iqdz7VYR4O8ZvietELb81iI4PaC49W6g==
influx.org=Academie
influx.bucket=TOCKEN

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mohamedkhmili13@gmail.com
spring.mail.password=aqiq hepy sdcp zhcz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/iot_alert
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Debug Hibernate
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE