spring.application.name=service-collecte
server.port=8090
spring.cloud.version=2023.0.1

eureka.client.use-dns-for-fetching-service-urls=false
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.prefer-ip-address=true

influx.url=http://localhost:8086
influx.token=JDkrG5xFjIUSZTIN7A86YFgzjsueWtMc_io3UwKlKlhL6bReUuQNqK5Jkt_ilaI88PwKlmMx2mI_EzhPliv-PA==
influx.org=Academie
influx.bucket=TOCKEN

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
